services:
    syagr_page.page_manager:
        class: Syagr\PageBundle\Service\PageManager
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setTrans, ["@translator"]]